---
- name: Ensure required packages are installed
  apt:
    name:
      - python3-pip
      - acl
      - wget
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Add PostgreSQL official APT repository
  shell: |
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  args:
    creates: /etc/apt/sources.list.d/pgdg.list
  become: true

- name: Import PostgreSQL signing key
  shell: |
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install PostgreSQL {{ postgresql_version }}
  apt:
    name: "postgresql-{{ postgresql_version }}"
    state: present
  become: true

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes
