---
- name: Configure PostgreSQL on AWS EC2
  hosts: aws_ec2
  gather_facts: yes
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: ap-southeast-1
    ansible_aws_ssm_bucket_name: terraform-bucket-ansible-ssm-gaurav
  roles:
    - role: postgress
